// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR1kvZWsM69Sw1Z-2HuyxaKoqEkX-3T6s',
    appId: '1:832508490629:web:3a687e3ccecf288cdc4aec',
    messagingSenderId: '832508490629',
    projectId: 'fitnessandposedetectionapp',
    authDomain: 'fitnessandposedetectionapp.firebaseapp.com',
    storageBucket: 'fitnessandposedetectionapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7WgpfDDOFfOqYyn_F7DRGxzxcWkhsNs',
    appId: '1:832508490629:android:480a5d30653e4ea1dc4aec',
    messagingSenderId: '832508490629',
    projectId: 'fitnessandposedetectionapp',
    storageBucket: 'fitnessandposedetectionapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mwcDt5m1SclaV_OxMSg45vKx9xLRxdk',
    appId: '1:832508490629:ios:265726283ee2d375dc4aec',
    messagingSenderId: '832508490629',
    projectId: 'fitnessandposedetectionapp',
    storageBucket: 'fitnessandposedetectionapp.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAndAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7mwcDt5m1SclaV_OxMSg45vKx9xLRxdk',
    appId: '1:832508490629:ios:265726283ee2d375dc4aec',
    messagingSenderId: '832508490629',
    projectId: 'fitnessandposedetectionapp',
    storageBucket: 'fitnessandposedetectionapp.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAndAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR1kvZWsM69Sw1Z-2HuyxaKoqEkX-3T6s',
    appId: '1:832508490629:web:06261c8118a9a761dc4aec',
    messagingSenderId: '832508490629',
    projectId: 'fitnessandposedetectionapp',
    authDomain: 'fitnessandposedetectionapp.firebaseapp.com',
    storageBucket: 'fitnessandposedetectionapp.firebasestorage.app',
  );
}
